---
  - name: Web server initial configuration
    hosts: all
    become: true

    tasks:
      - name: Ensure apache is at the latest version
        yum:
          name: httpd
          state: latest
      - name: Ensure apache is running
        service:
          name: httpd
          state: started

      - name: Install git and vim
        tags: always
        yum:
          name: 
            - vim
            - git
          state: latest
          update_cache: yes